/*
 * nrf24l01_registers.hpp
 *
 *  Created on: Jul 3, 2025
 *      Author: Oleksiy
 */

#ifndef NIKOLEX_NRF24L01_REGISTERS_HPP_
#define NIKOLEX_NRF24L01_REGISTERS_HPP_

namespace nikolex::nrf24l01 {

	enum REGISTER{
		CONFIG_REGISTER,
		EN_AA_REGISTER,
		EN_RXADDR_REGISTER,
		SETUP_AW_REGISTER,
		SETUP_RETR_REGISTER,
		RF_CH_REGISTER,
		RF_SETUP_REGISTER,
		STATUS_REGISTER,
		OBSERVE_TX_REGISTER,
		RPD_REGISTER,
		RX_ADDR_P0_REGISTER,
		RX_ADDR_P1_REGISTER,
		RX_ADDR_P2_REGISTER,
		RX_ADDR_P3_REGISTER,
		RX_ADDR_P4_REGISTER,
		RX_ADDR_P5_REGISTER,
		TX_ADDR_REGISTER,
		RX_PW_P0_REGISTER,
		RX_PW_P1_REGISTER,
		RX_PW_P2_REGISTER,
		RX_PW_P3_REGISTER,
		RX_PW_P4_REGISTER,
		RX_PW_P5_REGISTER,
		FIFO_STATUS_REGISTER,
		ACK_PLD_REGISTER,
		TX_PLD_REGISTER,
		RX_PL_REGISTER,
		DYNPD_REGISTER       = 0x1C,
		FEATURE_REGISTER
	};

}





#endif /* NIKOLEX_NRF24L01_REGISTERS_HPP_ */
